# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'TacgegraphCar' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'YTKNetwork'
pod 'Mantle'
pod 'MagicalRecord'
pod 'Masonry'
pod 'IQKeyboardManager'
pod 'SDWebImage'
pod 'pop'
pod 'MJRefresh'
pod 'SWTableViewCell'
pod 'LCProgressHUD'
pod 'VTMagic'

end
